<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DAFTAR</name>
   <tag></tag>
   <elementGuidId>cddb0498-9dcc-48bf-be67-39209000854c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf931616-febb-4b27-bf47-38b7bc566eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c3f0750-9336-44e3-a4d4-0570c216fb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary --rounded shadow</value>
      <webElementGuid>01363359-f6c0-487c-aeaa-77a737e989c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>01be5965-4df6-4c39-86cb-a23429658803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                DAFTAR
                            </value>
      <webElementGuid>f43bfc98-0369-430b-aa1c-69af4bc54cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_register&quot;)/div[@class=&quot;content justify-content-center register&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;registration__navigation-wrapper row justify-content-center&quot;]/div[@class=&quot;col-12 col-md-6&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;registration__navigation&quot;]/div[@class=&quot;registration__navigation-submit&quot;]/button[@id=&quot;submitButton&quot;]</value>
      <webElementGuid>6891bed5-acd1-4cb7-9ac7-53a44f7a0be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitButton']</value>
      <webElementGuid>28e588a1-5f02-405e-8c88-47a8dbed26e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_register']/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>adddd595-5e58-4d0c-9507-325bdc4bf956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirimkan Sekarang'])[1]/following::button[1]</value>
      <webElementGuid>d628986c-2818-443b-a387-c8fb3c4da244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Handphone Anda'])[1]/following::button[2]</value>
      <webElementGuid>ed5c6f7f-c494-48e5-a24a-f92256008384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk di sini'])[1]/preceding::button[1]</value>
      <webElementGuid>23f66aa4-c5f2-4d80-8361-aede4cacadad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari lebih lanjut.'])[1]/preceding::button[1]</value>
      <webElementGuid>45849eab-e57f-4110-94c1-fd6ba9eb6b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAFTAR']/parent::*</value>
      <webElementGuid>0a03840a-8188-4af0-952e-dec6c75cdb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>29e9136d-6e6d-46de-b2a7-220a8b7f3b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'submitButton' and (text() = '
                                DAFTAR
                            ' or . = '
                                DAFTAR
                            ')]</value>
      <webElementGuid>33805431-faec-4454-8340-65c44027c61e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
