<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>1e80e5c7-4978-47f0-a6e0-b37ad84c3638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginOtpAction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='loginOtpAction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>946d0e90-bcb8-4abf-8310-179752c47180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c3dc679-3654-4077-923b-587b011f5378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn --primary-reverse loginOtpAction</value>
      <webElementGuid>65fbee1c-978a-43fa-8f29-b376931fe6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginOtpAction</value>
      <webElementGuid>66b9a2b9-bda2-4741-b17b-83dade1a981c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>34c72495-6ff4-4149-8667-99872af6d87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginOtpAction&quot;)</value>
      <webElementGuid>ba5703fb-b599-4094-a70d-9e263e74d5f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='loginOtpAction']</value>
      <webElementGuid>7a2862a2-2668-4f4e-88b6-96c5d2c13e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div[5]/button</value>
      <webElementGuid>36fbc003-e6f7-4283-8c2d-ad51276c5ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Ulang'])[1]/following::button[1]</value>
      <webElementGuid>277d8ba0-b0d9-45da-bfe5-d358edccc4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode OTP'])[1]/following::button[2]</value>
      <webElementGuid>383b6c6a-7f34-4ed8-9111-5ef6632eadaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halaman ini dilindungi oleh Google ReCAPTCHA.'])[1]/preceding::button[1]</value>
      <webElementGuid>f7003288-bc00-4480-bb4a-564d2f5bd189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari lebih lanjut.'])[1]/preceding::button[1]</value>
      <webElementGuid>8192c8fc-9dc7-411d-8a93-bf15e1cb39e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>d4ecc426-12e2-4832-a8fe-2b20153a05f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'loginOtpAction' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>5f92dc4c-b103-40b5-89dc-0ce359dd77a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
