<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0ed84de0-fc61-4c6a-87f8-a9e83aad5981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;close&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67f6dfc6-96a1-41cf-b343-dcb0d3ad5cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/x.png</value>
      <webElementGuid>63c2b88b-8571-4c72-ab8d-f658dc049717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>00633191-5817-4ab4-98bc-ee2ab2cebb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>3507093139</value>
      <webElementGuid>c507dc0a-3844-467f-b503-8c89d555b3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>720e229f-5e03-4baf-8aae-521e70909c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;modal-sukses-otp-form show&quot;]/div[@class=&quot;modal-sukses-otp-form_iner&quot;]/div[@class=&quot;modal-sukses-otp-form_close&quot;]/img[1]</value>
      <webElementGuid>3a730533-07fd-41f5-9f63-3cb9eecd6fe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>15660f9d-06ee-4ed5-a2ca-a574181130ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>584af2b9-482b-4aa4-a92e-05a268294b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/x.png' and @alt = 'close']</value>
      <webElementGuid>c9067590-01a0-4640-a19b-cc35d1545039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
