<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode OTP_otp-login-form_1</name>
   <tag></tag>
   <elementGuidId>4defebe2-c1f6-4c02-b907-e4968ebe69cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>586d0b2c-9ee5-4eea-9925-855a993e6727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>5465a050-05f8-4feb-bbcb-1da1157e8146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control otp-item-page</value>
      <webElementGuid>39a8a9ff-3550-49fb-bc29-a3f84d881cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-2</value>
      <webElementGuid>8a84dab8-6fd0-4fb8-9a75-088f8e2059b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3d3a3a67-a1fe-4111-b79e-5ad1f4f8c65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>06456ade-8cb2-4f0d-8fef-8f3df6ccafd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-login-form</value>
      <webElementGuid>0e176343-33e8-4cd2-a1d0-21645b145d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-2&quot;)</value>
      <webElementGuid>1f8f6f31-0bff-4f2d-a6bc-3354d37892b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp-2']</value>
      <webElementGuid>571ce404-f76e-4a5d-a88d-c72d378846f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div[3]/div/input[2]</value>
      <webElementGuid>af7b70e1-fbc6-4f2e-86e1-a9f17ab18138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>02a38e0c-4170-4067-b375-7767dfda4b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'otp-2' and @placeholder = '-' and @name = 'otp-login-form']</value>
      <webElementGuid>bd4f3f3a-79e7-4047-bb3a-d9fefabd0669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
