<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP_username-login-otp</name>
   <tag></tag>
   <elementGuidId>4ceebb0e-49c4-4a8e-bc81-d72dea7d5e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username-login-otp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username-login-otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c408c4c-79f0-446d-85eb-6ed1694f9872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0433bcb5-ac0a-48c6-9dc2-8ea97f9fd0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username-login-otp</value>
      <webElementGuid>41c1353b-b6f9-45e2-906c-bc8946350bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username-login-otp</value>
      <webElementGuid>2ec617a6-9082-4376-97fc-b69e1c283524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nomor hp</value>
      <webElementGuid>60c1e346-320e-4bb6-a6f8-a89fbe1a7647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>18d4f91d-38fb-474e-8bd6-3f7e8a51e67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>a5541877-8ad3-4136-a452-394877f3ba5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username-login-otp&quot;)</value>
      <webElementGuid>c66dabf4-2e04-4768-9e6d-e7dee0eef36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username-login-otp']</value>
      <webElementGuid>0bbc9273-1489-45d9-a76e-3905e437a139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div/input[3]</value>
      <webElementGuid>4d7f13fa-8d98-4b68-829a-66100717d668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[3]</value>
      <webElementGuid>42dea46d-5222-40fc-89f6-7adf111ff469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username-login-otp' and @id = 'username-login-otp' and @placeholder = 'Masukkan nomor hp']</value>
      <webElementGuid>d8de8b68-c73b-4817-a753-84036f4af253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
