<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode OTP_otp-login-form_1_2_3</name>
   <tag></tag>
   <elementGuidId>d120396a-e60d-40e5-92aa-a0825a3d0afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84b871f5-0ed8-40b2-8013-6ed7a763012b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>953c7c9e-45c0-4cdf-a638-25118c391cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control otp-item-page</value>
      <webElementGuid>72c8022f-6604-446f-be11-8d46aa660906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-4</value>
      <webElementGuid>32d86975-5fa9-490e-9675-f9854790706a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>820c060c-3769-4c88-827b-1f5d946aad4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>d899461d-a37f-4ff7-a858-dbf853c78072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-login-form</value>
      <webElementGuid>6c552b3c-9a0e-4417-bcfa-8d7a28811a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-4&quot;)</value>
      <webElementGuid>bbb1e876-476a-47da-8f32-a1bd3bdaeca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp-4']</value>
      <webElementGuid>f5149df1-cee2-4019-b715-462ef105be89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div[3]/div/input[4]</value>
      <webElementGuid>8d6cc696-b627-4a02-96ab-47c9083bb03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[4]</value>
      <webElementGuid>588123a4-829d-4d2c-bbf0-5b140873bcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'otp-4' and @placeholder = '-' and @name = 'otp-login-form']</value>
      <webElementGuid>b090a8c9-8310-4856-8c61-ad7729a706e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
