<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode OTP_otp-login-form</name>
   <tag></tag>
   <elementGuidId>b2101c69-04b4-40ab-bfeb-bed85cb8d2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbb05de6-991e-4021-a893-57cfcd83f505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>902a5bdc-9216-4f5b-ba95-ee9a613b9cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control otp-item-page</value>
      <webElementGuid>8f3112a7-a470-4399-bdb0-10749dd7c916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-1</value>
      <webElementGuid>3b829381-2178-46fa-91c4-2175ed7ddf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6fd6d2e7-35b4-42f8-956a-ec3fd0a34dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>7160ecec-ef12-4ab3-9b1a-1c63c9c4f5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-login-form</value>
      <webElementGuid>26f111ff-33e9-4878-8def-f87f3b171ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-1&quot;)</value>
      <webElementGuid>71f1fe8e-807f-45ae-a23e-a72e009c8149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp-1']</value>
      <webElementGuid>fb286d8d-9b02-41b4-8b09-a11e87aea812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div[3]/div/input</value>
      <webElementGuid>1767b418-d91f-45eb-bb46-6bac25d6383c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3d00cc29-50fc-4213-ba4d-d741b8471218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'otp-1' and @placeholder = '-' and @name = 'otp-login-form']</value>
      <webElementGuid>37449465-3ba3-4d61-9074-230fbfbe3123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
