<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode OTP_otp-login-form_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>ca450bbe-e718-42bf-b98f-a567c47cbdfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf13105b-f196-4ae9-87b2-78cfebe93633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8675c32b-02e6-46eb-8b64-a586d1378c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control otp-item-page</value>
      <webElementGuid>ce53be26-4742-4962-929a-c8b9c1d0a8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-5</value>
      <webElementGuid>ccd40646-1819-46bd-af68-d48cd0704d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9991eb7-8e55-4676-9e1d-5e5fa8d7a2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>e225b143-6166-4ff1-b66a-b6dfb5fc542d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-login-form</value>
      <webElementGuid>3ce21045-e649-420e-b347-4ba8784c0aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-5&quot;)</value>
      <webElementGuid>6402dfba-424b-4fd6-b603-1a3e1822e6a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp-5']</value>
      <webElementGuid>1bfa0bbb-dbef-4541-bd81-7ca8a09f4e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div[3]/div/input[5]</value>
      <webElementGuid>014b9d66-c401-4f58-9a21-ea14ae4dce0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[5]</value>
      <webElementGuid>4f7c942b-9726-4c86-b024-4745202e0722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'otp-5' and @placeholder = '-' and @name = 'otp-login-form']</value>
      <webElementGuid>9e1f97e2-9054-4a29-a09d-439fd031dba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
