<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode OTP_otp-login-form_1_2</name>
   <tag></tag>
   <elementGuidId>bc1ea0c1-8b74-45db-926e-ee86dc12422f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5569449f-08c3-46b9-bb62-cc3ac42bf3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>7b30bc75-58ba-4fa2-8ac7-4b9f8f5e3029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control otp-item-page</value>
      <webElementGuid>aacef7be-e5a1-4c97-86ca-a0841f276380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-3</value>
      <webElementGuid>1a27e097-b77c-4c5e-8713-d795c2da84ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>27e932b1-66e9-4470-bdd1-991e1c0550e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>4b23b5d8-bba9-43e7-9869-6021f86f2c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-login-form</value>
      <webElementGuid>c505f92f-b4ed-41e1-813f-85343161a051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-3&quot;)</value>
      <webElementGuid>b8f5e84e-edc5-4aa3-8e94-8befe5216e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp-3']</value>
      <webElementGuid>5a4b421b-a3ec-4e07-a54a-2c6742603a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-otp']/div[3]/div/input[3]</value>
      <webElementGuid>2328d5c3-2df9-423e-9713-6999c28500ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[3]</value>
      <webElementGuid>56445de3-76d7-42ae-9b80-427078799c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'otp-3' and @placeholder = '-' and @name = 'otp-login-form']</value>
      <webElementGuid>7c5acd69-1000-4eb0-aaf5-545cf0d63844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
