<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_mama</name>
   <tag></tag>
   <elementGuidId>b812a689-e0ac-46bc-a757-dbb56b12dfed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//picture[@class='image-other']//img</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
