<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kondisi Bunda</name>
   <tag></tag>
   <elementGuidId>84cdfcff-0258-48c8-ad2a-8d610b20d6c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kondisi-bunda</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kondisi-bunda']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7ffe85e-abff-408c-800b-467f9d1b1998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kondisi-bunda</value>
      <webElementGuid>04d3a86e-579a-4040-90a3-9a486cda0ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>93131e1e-fb68-43b4-bb3a-31a136b154ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kondisi Bunda</value>
      <webElementGuid>d0235d7a-73a5-4abe-998d-4dcf4fe3fa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kondisi-bunda&quot;)</value>
      <webElementGuid>1cef7c4f-3534-41a1-b566-92b808bf8240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='kondisi-bunda']</value>
      <webElementGuid>d9608229-efd6-4bf6-9c0c-654b45ab5293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[4]/div</value>
      <webElementGuid>d936fbdd-cbb6-4f4f-b22d-ea0131dcdad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Bunda (Kehamilan dan Anak)'])[1]/following::div[1]</value>
      <webElementGuid>241b8472-8ea1-46a0-ad80-6f364ac5e1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil'])[1]/preceding::div[1]</value>
      <webElementGuid>00b0fd37-390c-46f9-acc0-314ace97fecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil &amp; Memiliki Anak'])[1]/preceding::div[2]</value>
      <webElementGuid>d883142a-d850-4869-afa1-45b67897ae09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kondisi Bunda']/parent::*</value>
      <webElementGuid>887a09ae-364b-434b-91de-519cd9d9828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div</value>
      <webElementGuid>9f4fe980-f891-45cc-9350-94dcb0dd2492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'kondisi-bunda' and (text() = 'Kondisi Bunda' or . = 'Kondisi Bunda')]</value>
      <webElementGuid>2dda54e5-e7c5-4fc7-af72-f4a24a7fb9fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
