<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Ponsel_msisdn</name>
   <tag></tag>
   <elementGuidId>90f410cd-9ecd-43c5-95a4-2dac897037b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a802aa53-4879-4e99-bc48-cfea5a2ccd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>msisdn</value>
      <webElementGuid>7fa35883-fdc5-4d12-803e-98d9c3e75919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f63e68b-b0a3-4445-98be-c4f16ebb04bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>4fe73ebf-6319-4809-8b99-af7726700ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control getmsisdn</value>
      <webElementGuid>f6c155e1-3746-429b-beb1-fe184a1d6627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mohon Isikan Nomor Ponsel Bunda</value>
      <webElementGuid>a085a390-cdc9-4afa-9fdd-0f3dc1ac2231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;handphone&quot;)</value>
      <webElementGuid>ab3b71ce-042f-4838-ac1d-4428c3161818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='handphone']</value>
      <webElementGuid>d9a4d40d-a4d3-49ca-ae45-c9894a83afb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[2]/input</value>
      <webElementGuid>86be6b97-71a5-49b4-8b3f-0241673852d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>decefab8-d675-4de7-87e1-41de3d585bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'msisdn' and @type = 'text' and @id = 'handphone' and @placeholder = 'Mohon Isikan Nomor Ponsel Bunda']</value>
      <webElementGuid>9827d7d8-c067-4909-98ae-e4e89c544d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
