<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_firstname</name>
   <tag></tag>
   <elementGuidId>7fb605e3-ac3b-47d9-95f1-5d417871f2e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namalengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namalengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99185a88-af3d-47f4-b385-d464a63660cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>4e5bfdd4-f9ff-4651-b0a2-e1caafb19093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b111211-ddae-4a75-945f-de7ac0b2d13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namalengkap</value>
      <webElementGuid>6b0a20b4-9e92-462c-8fe9-e73d362ecfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>30729271-87aa-4586-9b61-824b25f57b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mohon Isikan Nama Lengkap Bunda</value>
      <webElementGuid>fe663ee7-424c-4bd6-a5d0-2e6c80884937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namalengkap&quot;)</value>
      <webElementGuid>d5dabbb5-eb5c-4881-bdd1-8aea2183a45d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namalengkap']</value>
      <webElementGuid>ce47fedc-9967-45f2-874e-6dd95e30a8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div/input[3]</value>
      <webElementGuid>feb3fd62-6226-4d0b-8fc2-fbf33e7c4085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>5e908b06-b444-4138-badd-d2d818b548f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'firstname' and @type = 'text' and @id = 'namalengkap' and @placeholder = 'Mohon Isikan Nama Lengkap Bunda']</value>
      <webElementGuid>9ef568e4-290e-4d27-afae-d40512df1dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
