<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya telah membacadan_sayasetuju</name>
   <tag></tag>
   <elementGuidId>575f89a7-f1e7-4c6a-a6c2-e898cf59a026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sayasetuju</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sayasetuju']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72fecb08-78c6-4755-b6dd-ebc6ec7f9bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>009dce6b-fb4e-44c3-9743-dc9a6c6a6dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b352063e-159d-4d29-acdb-bb8de13b668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sayasetuju</value>
      <webElementGuid>4326976f-9f6f-4b6e-8069-9c8b04409c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sayasetuju&quot;)</value>
      <webElementGuid>fbd1e93c-400d-46d9-9785-c915a6264991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sayasetuju']</value>
      <webElementGuid>3c0a94ae-fd01-47c2-8d5e-cd27b1e31f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[10]/div/input</value>
      <webElementGuid>d597e7f3-1fa7-4077-8732-65b66e9b66ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>c036420b-5385-4cf0-8a48-600120a29177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sayasetuju']</value>
      <webElementGuid>90d163b5-4906-4a40-ab45-f87528d52830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
