<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e0222865-2532-4e12-b1f7-75d86eebf9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-profile-completion-form_close > img[alt=&quot;close&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='close'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a7e6ec8-6f2d-4db9-80d4-2bad6461972e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/x.png</value>
      <webElementGuid>a4a5c476-7617-4351-98a1-6e7a219a3bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>817e443e-e68d-4eca-8601-badcd5a3eaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>3507093139</value>
      <webElementGuid>9d274b27-7944-4c64-bb2c-b23d3d597bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>bad73cdc-f65e-45af-927f-f9a19e2f7003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;membership-dashboard&quot;]/div[@class=&quot;modal-profile-completion-form show&quot;]/div[@class=&quot;modal-profile-completion-form_iner&quot;]/div[@class=&quot;modal-profile-completion-form_close&quot;]/img[1]</value>
      <webElementGuid>c6298bd6-bb0b-4fee-8e78-e31c279e809f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='close'])[6]</value>
      <webElementGuid>f46e612d-c97c-485f-a1b5-c041bea83db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/img</value>
      <webElementGuid>0acb4194-447d-446b-a425-8fcf126a9d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/x.png' and @alt = 'close']</value>
      <webElementGuid>d8a66984-e4d3-4424-8073-5d804a2b3e37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
