<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk Tanpa Password</name>
   <tag></tag>
   <elementGuidId>27b85948-3de5-4b67-a28b-37aa10b999ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginotpcta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='loginotpcta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05a78c64-d104-47d2-99be-ba4d1791a64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/membership/login-otp</value>
      <webElementGuid>8611ff08-71d9-4f3b-a7ba-36b58b78e956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn --primary-reverse loginotpcta</value>
      <webElementGuid>599bb021-b2cb-43b6-b6f7-11516b402f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginotpcta</value>
      <webElementGuid>64c186a0-0e59-4145-8afb-04bfda6fa2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk Tanpa Password</value>
      <webElementGuid>5a348148-1a12-44a0-8247-609f06154c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginotpcta&quot;)</value>
      <webElementGuid>29e9aa87-ab0c-4a8f-ad72-6c67223c2ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='loginotpcta']</value>
      <webElementGuid>e681234c-a287-498c-b4db-4ccf0fa01964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-password']/div[5]/a</value>
      <webElementGuid>357aecd7-b98f-4006-ab41-6a0bb4ca5b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk Tanpa Password')]</value>
      <webElementGuid>6c795cb8-a9b5-4ec7-a64d-84d6bad442b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[4]/following::a[1]</value>
      <webElementGuid>1f0a5c1c-6537-4e18-92f6-096389641472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password'])[1]/following::a[1]</value>
      <webElementGuid>d92a2772-5b5b-4d55-9b10-3c3d5552fe89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/preceding::a[1]</value>
      <webElementGuid>19d046b0-925b-45ae-a0c7-f0f951c7fdc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk Tanpa Password']/parent::*</value>
      <webElementGuid>c192bc8f-c394-42f8-bcfc-39ec794597f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/membership/login-otp')]</value>
      <webElementGuid>cc0b56f2-bbfa-4af2-8637-0f7494e39129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/a</value>
      <webElementGuid>7f1b2ca9-4f12-4fd1-90e9-2cf9e2fe55af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/membership/login-otp' and @id = 'loginotpcta' and (text() = 'Masuk Tanpa Password' or . = 'Masuk Tanpa Password')]</value>
      <webElementGuid>86f23956-9ee6-47da-a3d1-d71c917c1955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
