<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Struk 2_receipt-img</name>
   <tag></tag>
   <elementGuidId>77ca67af-8a31-4a6d-a059-ad014a5564be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='receipt-img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#receipt-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>263d284e-ff11-43d4-8bf3-ccfec316ab88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>receipt-img</value>
      <webElementGuid>078b3b2a-47c3-457b-be51-c679aa74e31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receipt-img</value>
      <webElementGuid>5b0229fc-ee60-4e16-847d-f54e642b3704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/rrr_images/receipt-submission/click-trigger-upload.png</value>
      <webElementGuid>600c70c2-2a1d-41ae-ac9f-5c56b193ae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>22e5bbec-762c-4344-956a-17022d012a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receipt-img&quot;)</value>
      <webElementGuid>50138e0b-751e-44d6-b285-4859b5fb45de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='receipt-img']</value>
      <webElementGuid>35ed80ce-8e0b-4d8d-8386-e33e4fe5e9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upload-receipt']/div[2]/div/div/img</value>
      <webElementGuid>dbbb12fe-16d2-45c6-ae77-b3af9cca3368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='upload'])[6]</value>
      <webElementGuid>2b766132-f078-443c-8067-0b636e1d36b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>2e59b3e5-9ec8-4343-8a52-971f6d0e7244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'receipt-img' and @src = '/assets/rrr_images/receipt-submission/click-trigger-upload.png' and @alt = 'upload']</value>
      <webElementGuid>b1f9a759-15ad-42d6-93f0-8258707fa867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
