<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Struk 2_receipt-img</name>
   <tag></tag>
   <elementGuidId>b394913f-20c6-420b-95c3-71e2e711c307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='receipt-img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#receipt-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>062283a3-7e65-4255-8a3b-2a341b6a1183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>receipt-img</value>
      <webElementGuid>0e838639-df16-410c-adb0-0d785983af6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receipt-img</value>
      <webElementGuid>e681a0b0-265b-4f7d-a319-73a1ee966ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/rrr_images/receipt-submission/click-trigger-upload.png</value>
      <webElementGuid>9ec881e1-cd13-4c82-94a5-409a5d0a14e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>82d7e9c7-851f-4a71-8fd9-565baaed0aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receipt-img&quot;)</value>
      <webElementGuid>76d1540b-86db-40ee-8829-fe90b7d68388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='receipt-img']</value>
      <webElementGuid>0f245690-3014-4984-b585-d7f09b38e0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upload-receipt']/div[2]/div/div/img</value>
      <webElementGuid>cf497f57-8dd1-483d-9d37-27f68e3b09f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='upload'])[6]</value>
      <webElementGuid>51b253d1-9e85-4fdf-8d0e-afad80b0f8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>dfef32a7-7361-43d8-ae14-bbb6e8409133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'receipt-img' and @src = '/assets/rrr_images/receipt-submission/click-trigger-upload.png' and @alt = 'upload']</value>
      <webElementGuid>15bae1b2-20fe-4a66-b29a-e8e9079355b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
